# Generated by Django 5.0.3 on 2024-03-24 17:45

import django.core.validators
import django.db.models.deletion
import djgeojson.fields
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Drawing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Name of the drawing",
                        max_length=50,
                        verbose_name="Name",
                    ),
                ),
                (
                    "dxf",
                    models.FileField(
                        max_length=200,
                        upload_to="uploads/djeocad/dxf/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["dxf"]
                            )
                        ],
                        verbose_name="DXF file",
                    ),
                ),
                (
                    "geom",
                    djgeojson.fields.PointField(null=True, verbose_name="Location"),
                ),
                (
                    "designx",
                    models.FloatField(default=0, verbose_name="Design point X..."),
                ),
                ("designy", models.FloatField(default=0, verbose_name="...Y")),
                ("rotation", models.FloatField(default=0, verbose_name="Rotation")),
                (
                    "needs_refresh",
                    models.BooleanField(
                        default=True,
                        editable=False,
                        verbose_name="Refresh DXF file from layers",
                    ),
                ),
                (
                    "epsg",
                    models.IntegerField(
                        editable=False, null=True, verbose_name="CRS code"
                    ),
                ),
                (
                    "image",
                    filer.fields.image.FilerImageField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drawing_image",
                        to=settings.FILER_IMAGE_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Drawing",
                "verbose_name_plural": "Drawings",
            },
        ),
    ]
