# Generated by Django 5.0.3 on 2024-03-26 17:13

import django.db.models.deletion
import djgeojson.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djeocadengine", "0002_layer_layer_unique_layer_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.JSONField(null=True)),
                ("data", models.JSONField(null=True)),
                ("geom", djgeojson.fields.GeometryCollectionField()),
                ("insertion", djgeojson.fields.PointField(null=True)),
            ],
            options={
                "verbose_name": "Entity",
                "verbose_name_plural": "Entities",
            },
        ),
        migrations.AlterModelOptions(
            name="layer",
            options={
                "ordering": ("name",),
                "verbose_name": "Layer",
                "verbose_name_plural": "Layers",
            },
        ),
        migrations.RemoveConstraint(
            model_name="layer",
            name="unique_layer_name",
        ),
        migrations.AddField(
            model_name="layer",
            name="is_block",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="entity",
            name="layer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_entities",
                to="djeocadengine.layer",
            ),
        ),
    ]
