# Generated by Django 5.0.3 on 2024-03-28 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djeocadengine", "0003_entity_alter_layer_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="drawing",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parent_drawing",
                to="djeocadengine.drawing",
                verbose_name="Parent Drawing",
            ),
        ),
    ]
