# Generated by Django 5.0.3 on 2024-04-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djeocadengine", "0004_drawing_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="drawing",
            name="temp_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
