# Generated by Django 5.0.3 on 2024-04-05 14:22

import djgeojson.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djeocadengine", "0005_drawing_temp_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entity",
            name="label",
        ),
        migrations.AddField(
            model_name="layer",
            name="geom",
            field=djgeojson.fields.GeometryCollectionField(null=True),
        ),
        migrations.AlterField(
            model_name="drawing",
            name="temp_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Image"
            ),
        ),
    ]
