# Generated by Django 5.0.3 on 2024-04-08 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djeocadengine", "0006_remove_entity_label_layer_geom_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drawing",
            name="needs_refresh",
        ),
    ]
