# Generated by Django 5.0.6 on 2024-06-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djeocadengine", "0008_drawing_lat_drawing_long"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drawing",
            name="lat",
            field=models.FloatField(null=True, verbose_name="Latitude"),
        ),
        migrations.AlterField(
            model_name="drawing",
            name="long",
            field=models.FloatField(null=True, verbose_name="Longitude"),
        ),
    ]
